// Type-only import — erased at build so jsPDF (~300 KB) stays out of
// the bundle that imports this module. The constructor is loaded
// lazily inside openEligibilityPdf via dynamic import.
import type { jsPDF } from 'jspdf';

// One-page, Seven Arrows-branded insurance eligibility PDF.
//
// Renders the 271 response stored on a VOB row into a single letter
// page using pure jsPDF primitives plus an embedded logo PNG. All
// text stays selectable; the file ends up ~300KB (logo dominates).
//
// Layout, top to bottom:
//   1. Branded header band (logo inverted onto dark sienna)
//   2. Patient name hero + status verdict pill
//   3. Patient / Insurance two-column data card
//   4. Benefits matrix tiles (deductible, OOP, copay, coinsurance, dates)
//   5. Covered-services chip row
//   6. Notes / warnings strip (Stedi aaaErrors, etc.)
//   7. Branded footer band (contact info, trace id, generated by)
//
// The shape of `eligibility_response` follows Stedi's JSON 271 model.
// Keys we lean on:
//   planStatus[]              { statusCode, planCoverageDescription, serviceTypeCodes, planDateInformation? }
//   benefitsInformation[]     { code, name, serviceTypeCodes, inPlanNetworkIndicator, benefitAmount, benefitPercent, benefitDate }
//   subscriber                { firstName, lastName, dateOfBirth, memberId }
//   payer                     { name, payorIdentification }
//   errors[] / payer.aaaErrors

// ─── Brand tokens ──────────────────────────────────────────────────

const PAGE_W = 612;
const PAGE_H = 792;
const MARGIN_X = 40;

const COLOR = {
  ink: '#1a1a1a',
  body: '#3a2a22',
  muted: '#71665e',
  faint: '#a89d93',
  hairline: '#e6dfd5',
  cardBg: '#f5f0eb',
  cardBgAlt: '#ede4da',
  primary: '#bc6b4a',
  primaryDark: '#6b2a14',
  accent: '#d88966',
  deep: '#2a0f0a',
  white: '#ffffff',
  emerald: '#0f7a4a',
  emeraldBg: '#dff3e7',
  amber: '#a76712',
  amberBg: '#fbecd1',
  red: '#a01f1f',
  redBg: '#f7dada',
  blue: '#1d4a87',
  blueBg: '#e4ecf6',
} as const;

// ─── ASCII safety (Helvetica WinAnsi can't render fancy glyphs) ───

function asciiSafe(input: string | null | undefined): string {
  if (!input) return '';
  return String(input)
    .replace(/≥/g, '>=')
    .replace(/≤/g, '<=')
    .replace(/→/g, '->')
    .replace(/←/g, '<-')
    .replace(/—|–/g, '-')
    .replace(/•/g, '-')
    .replace(/[‘’]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/…/g, '...')
    .replace(/©/g, '(c)');
}

// ─── Eligibility response parser ──────────────────────────────────

type Verdict = 'active' | 'inactive' | 'review';

interface Highlights {
  verdict: Verdict;
  verdictLabel: string;
  planName: string | null;
  effectiveDate: string | null;
  terminationDate: string | null;
  // tiles: [label, primary value, secondary value (optional)]
  tiles: Array<{ label: string; value: string; sub?: string }>;
  coveredServices: string[];
  warnings: string[];
}

const SERVICE_NICENAMES: Record<string, string> = {
  '1': 'Medical care',
  '30': 'Health benefit plan',
  '33': 'Chiropractic',
  '35': 'Dental care',
  '47': 'Hospital',
  '48': 'Hospital inpatient',
  '50': 'Hospital outpatient',
  '51': 'Hospital ER',
  '86': 'Emergency services',
  '88': 'Pharmacy',
  '98': 'Office visit',
  'A4': 'Psychiatric',
  'AD': 'Inpatient psychiatric',
  'AE': 'Psychiatric, outpatient',
  'AF': 'Psychiatric, day partial',
  'AG': 'Psychiatric, residential',
  'AI': 'Substance abuse',
  'AJ': 'Substance abuse, inpatient',
  'AK': 'Substance abuse, outpatient',
  'BH': 'Mental health',
  'MH': 'Mental health',
  'BG': 'Mental health, partial',
  'BF': 'Mental health, residential',
  'UC': 'Urgent care',
};

function parseHighlights(resp: Record<string, unknown> | null): Highlights {
  const empty: Highlights = {
    verdict: 'review',
    verdictLabel: 'Needs review',
    planName: null,
    effectiveDate: null,
    terminationDate: null,
    tiles: [],
    coveredServices: [],
    warnings: [],
  };
  if (!resp) return empty;

  const warnings: string[] = [];
  const aaaErrors = ((resp.payer as Record<string, unknown> | undefined)?.aaaErrors as Array<Record<string, unknown>>) || [];
  for (const e of aaaErrors) {
    const desc = String(e.description || '');
    const code = String(e.code || '');
    if (desc) warnings.push(`AAA${code ? ' ' + code : ''}: ${desc}`);
  }
  const errors = (resp.errors as Array<Record<string, unknown>>) || [];
  for (const e of errors) {
    const desc = String(e.description || '');
    if (desc && !warnings.includes(desc)) warnings.push(desc);
  }

  const planStatus = (resp.planStatus as Array<Record<string, unknown>>) || [];
  let verdict: Verdict = warnings.length > 0 && planStatus.length === 0 ? 'review' : 'review';
  let verdictLabel = 'Needs review';
  let planName: string | null = null;
  for (const p of planStatus) {
    const sc = String(p.statusCode || '').toUpperCase();
    const name = (p.planCoverageDescription as string) || null;
    if (!planName && name) planName = name;
    if (sc === '1' || sc === 'A') {
      verdict = 'active';
      verdictLabel = 'Active coverage';
      break;
    }
    if (sc === '6' || sc === 'I' || sc === '7') {
      verdict = 'inactive';
      verdictLabel = 'Inactive';
    }
  }
  if (planStatus.length === 0 && warnings.length === 0) {
    verdict = 'review';
    verdictLabel = 'Needs review';
  }

  // Pull benefit summary fields.
  const benefits = (resp.benefitsInformation as Array<Record<string, unknown>>) || [];

  let effectiveDate: string | null = null;
  let terminationDate: string | null = null;
  const tiles: Array<{ label: string; value: string; sub?: string }> = [];

  const pickAmount = (code: string, networkPref?: 'Y' | 'N'): { in?: string; out?: string } => {
    let inAmt: string | undefined;
    let outAmt: string | undefined;
    for (const b of benefits) {
      if (String(b.code || '') !== code) continue;
      const amt = (b.benefitAmount as string) || (b.benefitPercent as string);
      if (!amt) continue;
      const net = String(b.inPlanNetworkIndicator || '').toUpperCase();
      const formatted = formatBenefitValue(amt, b.benefitPercent ? '%' : '$');
      if (net === 'Y') inAmt = formatted;
      else if (net === 'N') outAmt = formatted;
      else if (!inAmt) inAmt = formatted;
    }
    if (networkPref === 'Y') return { in: inAmt };
    if (networkPref === 'N') return { out: outAmt };
    return { in: inAmt, out: outAmt };
  };

  const deductible = pickAmount('C');
  const oopMax = pickAmount('G');
  const copay = pickAmount('B');
  const coinsurance = pickAmount('A');

  // Effective / termination dates from any benefit dateRange.
  for (const b of benefits) {
    const dt = b.benefitDate as Record<string, unknown> | string | undefined;
    if (dt && typeof dt === 'object') {
      const start = dt.startDate as string | undefined;
      const end = dt.endDate as string | undefined;
      if (start && !effectiveDate) effectiveDate = start;
      if (end && !terminationDate) terminationDate = end;
    } else if (typeof dt === 'string' && !effectiveDate) {
      effectiveDate = dt;
    }
  }

  // Build tiles in display order.
  tiles.push(makeTile('Plan status', verdictLabel, planName || undefined));
  tiles.push(makeTile('Deductible', deductible.in || '—', deductible.out ? `Out-of-net ${deductible.out}` : undefined));
  tiles.push(makeTile('Out-of-pocket max', oopMax.in || '—', oopMax.out ? `Out-of-net ${oopMax.out}` : undefined));
  tiles.push(makeTile('Co-pay', copay.in || '—', copay.out ? `Out-of-net ${copay.out}` : undefined));
  tiles.push(makeTile('Coinsurance', coinsurance.in || '—', coinsurance.out ? `Out-of-net ${coinsurance.out}` : undefined));
  tiles.push(
    makeTile(
      'Plan dates',
      effectiveDate ? formatPlanDate(effectiveDate) : '—',
      terminationDate ? `Ends ${formatPlanDate(terminationDate)}` : undefined,
    ),
  );

  // Covered service-type codes — gather distinct codes that appear
  // in either planStatus or benefitsInformation.
  const codeSet = new Set<string>();
  for (const p of planStatus) {
    const arr = (p.serviceTypeCodes as string[] | undefined) || [];
    for (const c of arr) codeSet.add(c);
  }
  for (const b of benefits) {
    const arr = (b.serviceTypeCodes as string[] | undefined) || [];
    for (const c of arr) codeSet.add(c);
  }
  const coveredServices: string[] = [];
  for (const code of codeSet) {
    const nice = SERVICE_NICENAMES[code];
    if (nice) coveredServices.push(nice);
  }

  return {
    verdict,
    verdictLabel,
    planName,
    effectiveDate,
    terminationDate,
    tiles,
    coveredServices: dedupe(coveredServices).slice(0, 12),
    warnings,
  };
}

function makeTile(label: string, value: string, sub?: string) {
  return { label, value, sub };
}

function formatBenefitValue(raw: string, kind: '$' | '%'): string {
  const n = Number(raw);
  if (!Number.isFinite(n)) return raw;
  if (kind === '%') return `${Math.round(n)}%`;
  return `$${n.toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 2 })}`;
}

function formatPlanDate(raw: string): string {
  // Stedi returns YYYYMMDD or YYYY-MM-DD
  const m = /^(\d{4})-?(\d{2})-?(\d{2})/.exec(raw);
  if (!m) return raw;
  const y = Number(m[1]);
  const mo = Number(m[2]);
  const d = Number(m[3]);
  const date = new Date(Date.UTC(y, mo - 1, d));
  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' });
}

function dedupe<T>(arr: T[]): T[] {
  return Array.from(new Set(arr));
}

// ─── Logo loading ────────────────────────────────────────────────

let logoCache: string | null = null;
async function loadLogoDataUrl(): Promise<string | null> {
  if (logoCache) return logoCache;
  if (typeof window === 'undefined') return null;
  try {
    const res = await fetch('/images/logo.png');
    if (!res.ok) return null;
    const blob = await res.blob();
    const reader = new FileReader();
    const dataUrl: string = await new Promise((resolve, reject) => {
      reader.onload = () => resolve(String(reader.result));
      reader.onerror = () => reject(reader.error);
      reader.readAsDataURL(blob);
    });
    logoCache = dataUrl;
    return dataUrl;
  } catch {
    return null;
  }
}

// ─── Primitive helpers ───────────────────────────────────────────

function setFill(pdf: jsPDF, hex: string) {
  const { r, g, b } = hexToRgb(hex);
  pdf.setFillColor(r, g, b);
}
function setStroke(pdf: jsPDF, hex: string) {
  const { r, g, b } = hexToRgb(hex);
  pdf.setDrawColor(r, g, b);
}
function setText(pdf: jsPDF, hex: string) {
  const { r, g, b } = hexToRgb(hex);
  pdf.setTextColor(r, g, b);
}
function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const h = hex.replace('#', '');
  return {
    r: parseInt(h.slice(0, 2), 16),
    g: parseInt(h.slice(2, 4), 16),
    b: parseInt(h.slice(4, 6), 16),
  };
}

function drawPill(
  pdf: jsPDF,
  x: number,
  y: number,
  text: string,
  opts: { fill: string; textColor: string; padX?: number; size?: number; bold?: boolean },
): number {
  const { fill, textColor, padX = 10, size = 10, bold = true } = opts;
  pdf.setFont('helvetica', bold ? 'bold' : 'normal');
  pdf.setFontSize(size);
  const w = pdf.getTextWidth(text) + padX * 2;
  const h = size + 8;
  setFill(pdf, fill);
  pdf.roundedRect(x, y - h + 4, w, h, h / 2, h / 2, 'F');
  setText(pdf, textColor);
  pdf.text(text, x + padX, y);
  return w;
}

// ─── Main entry ──────────────────────────────────────────────────

export interface EligibilityPdfRow {
  id: string;
  full_name: string;
  date_of_birth: string | null;
  phone: string | null;
  email: string | null;
  insurance_provider: string | null;
  member_id?: string | null;
  group_number?: string | null;
  payer_id?: string | null;
  payer_name?: string | null;
  subscriber_first_name?: string | null;
  subscriber_last_name?: string | null;
  subscriber_dob?: string | null;
  subscriber_relationship?: string | null;
  eligibility_response?: Record<string, unknown> | null;
  eligibility_checked_at?: string | null;
}

// When `existingWindow` is supplied and still open we navigate it to
// the new blob URL instead of spawning a fresh popup — this is what
// lets "Re-run eligibility check" refresh an already-open PDF
// viewer without leaving stale data on screen.
export async function openEligibilityPdf(
  row: EligibilityPdfRow,
  existingWindow?: Window | null,
): Promise<Window | null> {
  const resp = row.eligibility_response ?? null;
  const highlights = parseHighlights(resp);
  const logoDataUrl = await loadLogoDataUrl();
  const { jsPDF: JsPdfCtor } = await import('jspdf');
  const pdf = new JsPdfCtor({ unit: 'pt', format: 'letter' });

  drawHeaderBand(pdf, logoDataUrl, row);
  drawHero(pdf, row, highlights);
  drawDataCard(pdf, row);
  drawBenefitsMatrix(pdf, highlights);
  drawCoveredServices(pdf, highlights);
  drawWarnings(pdf, highlights);
  drawFooterBand(pdf, row);

  const blobUrl = pdf.output('bloburl') as unknown as string;

  if (existingWindow && !existingWindow.closed) {
    try {
      existingWindow.location.replace(blobUrl);
      existingWindow.focus();
      return existingWindow;
    } catch {
      // Cross-origin / blob navigation failures fall through to a
      // fresh window so the user still sees the updated PDF.
    }
  }

  const w = window.open(blobUrl, '_blank', 'noopener,noreferrer,width=900,height=1100');
  if (!w) {
    const safe = row.full_name.replace(/[^a-z0-9]+/gi, '-').toLowerCase() || 'patient';
    pdf.save(`eligibility-${safe}.pdf`);
    return null;
  }
  return w;
}

// ─── Section: header band ───────────────────────────────────────

function drawHeaderBand(pdf: jsPDF, logoDataUrl: string | null, row: EligibilityPdfRow) {
  const H = 78;
  setFill(pdf, COLOR.deep);
  pdf.rect(0, 0, PAGE_W, H, 'F');

  // Accent stripe along the bottom edge of the band.
  setFill(pdf, COLOR.primary);
  pdf.rect(0, H, PAGE_W, 3, 'F');

  // Logo (inverted: original is dark-on-light, we render the
  // dreamcatcher + wordmark over a dark band so we just place the
  // image — its multi-color gradient reads on the deep sienna).
  if (logoDataUrl) {
    try {
      const aspect = 3176 / 865;
      const logoH = 44;
      const logoW = logoH * aspect;
      pdf.addImage(logoDataUrl, 'PNG', MARGIN_X, (H - logoH) / 2, logoW, logoH, undefined, 'FAST');
    } catch {
      drawLogoFallback(pdf);
    }
  } else {
    drawLogoFallback(pdf);
  }

  // Right side: doc title + verification id
  setText(pdf, COLOR.white);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(10);
  pdf.text(asciiSafe('INSURANCE ELIGIBILITY VERIFICATION'), PAGE_W - MARGIN_X, 32, { align: 'right' });

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(8);
  setText(pdf, '#d8c8b8');
  const checkedAt = row.eligibility_checked_at
    ? new Date(row.eligibility_checked_at).toLocaleString('en-US', {
        month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit',
      })
    : new Date().toLocaleString('en-US');
  pdf.text(asciiSafe(`Verified ${checkedAt}`), PAGE_W - MARGIN_X, 48, { align: 'right' });

  const traceId = ((row.eligibility_response?.meta as Record<string, unknown> | undefined)?.traceId as string | undefined) || row.id;
  pdf.setFontSize(7);
  setText(pdf, '#a89484');
  pdf.text(asciiSafe(`Verification ID: ${traceId.slice(0, 36)}`), PAGE_W - MARGIN_X, 62, { align: 'right' });
}

function drawLogoFallback(pdf: jsPDF) {
  setText(pdf, COLOR.white);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(18);
  pdf.text(asciiSafe('SEVEN ARROWS'), MARGIN_X, 38);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(8);
  setText(pdf, '#d8c8b8');
  pdf.text(asciiSafe('RECOVERY'), MARGIN_X, 54);
}

// ─── Section: patient hero + status pill ─────────────────────────

function drawHero(pdf: jsPDF, row: EligibilityPdfRow, h: Highlights) {
  const TOP = 100;

  // Eyebrow label
  setText(pdf, COLOR.primary);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(8);
  pdf.text(asciiSafe('PATIENT'), MARGIN_X, TOP);

  // Big name in a serif (Times — selectable & built into jsPDF)
  setText(pdf, COLOR.ink);
  pdf.setFont('times', 'normal');
  pdf.setFontSize(32);
  pdf.text(asciiSafe(row.full_name || 'Unknown patient'), MARGIN_X, TOP + 26);

  // Sub-line: DOB + payer in muted body
  setText(pdf, COLOR.muted);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  const subParts: string[] = [];
  if (row.date_of_birth) subParts.push(`DOB ${formatPlanDate(row.date_of_birth)}`);
  const payer = row.payer_name || row.insurance_provider;
  if (payer) subParts.push(payer);
  if (h.planName) subParts.push(h.planName);
  pdf.text(asciiSafe(subParts.join('   '))  || '', MARGIN_X, TOP + 44);

  // Verdict pill on the right edge.
  const { fill, fg } = verdictColors(h.verdict);
  drawPill(pdf, PAGE_W - MARGIN_X - 1, TOP + 20, asciiSafe(h.verdictLabel.toUpperCase()), {
    fill,
    textColor: fg,
    size: 11,
    padX: 14,
    bold: true,
  });
  // The drawPill returns width starting from x, but here we want right-anchored.
  // Re-draw aligned right: clear and re-add manually.
  redrawPillRight(pdf, PAGE_W - MARGIN_X, TOP + 20, asciiSafe(h.verdictLabel.toUpperCase()), fill, fg);
}

function redrawPillRight(pdf: jsPDF, xRight: number, y: number, text: string, fill: string, fg: string) {
  // Overwrite the left-anchored pill with a properly right-anchored one.
  // We paint a small background-color rectangle behind first to mask
  // the earlier draw.
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(11);
  const w = pdf.getTextWidth(text) + 28;
  const h = 22;
  // Mask: paint page background (white) over the area where the
  // earlier left-anchored pill might be.
  setFill(pdf, COLOR.white);
  pdf.rect(MARGIN_X + 200, y - h + 4, PAGE_W - MARGIN_X - (MARGIN_X + 200), h, 'F');
  // Actual pill
  setFill(pdf, fill);
  pdf.roundedRect(xRight - w, y - h + 4, w, h, h / 2, h / 2, 'F');
  setText(pdf, fg);
  pdf.text(text, xRight - 14, y, { align: 'right' });
}

function verdictColors(v: Verdict): { fill: string; fg: string } {
  if (v === 'active') return { fill: COLOR.emerald, fg: COLOR.white };
  if (v === 'inactive') return { fill: COLOR.red, fg: COLOR.white };
  return { fill: COLOR.amber, fg: COLOR.white };
}

// ─── Section: data card (patient + insurance) ────────────────────

function drawDataCard(pdf: jsPDF, row: EligibilityPdfRow) {
  const TOP = 178;
  const H = 120;
  const COL_GAP = 18;
  const colW = (PAGE_W - MARGIN_X * 2 - COL_GAP) / 2;

  // Card background
  setFill(pdf, COLOR.cardBg);
  pdf.roundedRect(MARGIN_X, TOP, PAGE_W - MARGIN_X * 2, H, 8, 8, 'F');
  setStroke(pdf, COLOR.hairline);
  pdf.setLineWidth(0.6);
  pdf.roundedRect(MARGIN_X, TOP, PAGE_W - MARGIN_X * 2, H, 8, 8, 'S');

  // Vertical divider between columns
  setStroke(pdf, COLOR.hairline);
  pdf.line(MARGIN_X + colW + COL_GAP / 2, TOP + 16, MARGIN_X + colW + COL_GAP / 2, TOP + H - 16);

  drawCardColumn(pdf, MARGIN_X + 18, TOP + 18, colW - 18, 'PATIENT', [
    ['Name', row.full_name],
    ['Date of birth', row.date_of_birth ? formatPlanDate(row.date_of_birth) : '—'],
    ['Phone', row.phone || '—'],
    ['Email', row.email || '—'],
  ]);
  drawCardColumn(pdf, MARGIN_X + colW + COL_GAP + 18, TOP + 18, colW - 18, 'INSURANCE', [
    ['Payer', row.payer_name || row.insurance_provider || '—'],
    ['Member ID', row.member_id || '—'],
    ['Group #', row.group_number || '—'],
    [
      'Subscriber',
      [row.subscriber_first_name, row.subscriber_last_name].filter(Boolean).join(' ') || row.full_name,
    ],
    ['Relationship', row.subscriber_relationship || 'Self'],
  ]);
}

function drawCardColumn(
  pdf: jsPDF,
  x: number,
  y: number,
  width: number,
  heading: string,
  rows: Array<[string, string | null | undefined]>,
) {
  setText(pdf, COLOR.primary);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(8);
  pdf.text(asciiSafe(heading), x, y);

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(9);
  let cy = y + 16;
  for (const [label, raw] of rows) {
    const value = (raw || '—') as string;
    setText(pdf, COLOR.muted);
    pdf.text(asciiSafe(label), x, cy);
    setText(pdf, COLOR.ink);
    pdf.setFont('helvetica', 'bold');
    const wrapped = pdf.splitTextToSize(asciiSafe(value), width - 110) as string[];
    pdf.text(wrapped[0] || '—', x + 100, cy);
    pdf.setFont('helvetica', 'normal');
    cy += 17;
  }
}

// ─── Section: benefits matrix (2 rows x 3 columns) ───────────────

function drawBenefitsMatrix(pdf: jsPDF, h: Highlights) {
  const TOP = 318;
  const ROWS = 2;
  const COLS = 3;
  const GAP = 10;
  const usableW = PAGE_W - MARGIN_X * 2;
  const tileW = (usableW - GAP * (COLS - 1)) / COLS;
  const tileH = 80;

  // Section label
  setText(pdf, COLOR.primary);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(8);
  pdf.text(asciiSafe('BENEFITS SUMMARY'), MARGIN_X, TOP - 8);

  setStroke(pdf, COLOR.hairline);
  pdf.setLineWidth(0.5);
  pdf.line(MARGIN_X + 110, TOP - 11, PAGE_W - MARGIN_X, TOP - 11);

  for (let i = 0; i < ROWS * COLS; i++) {
    const tile = h.tiles[i];
    if (!tile) continue;
    const col = i % COLS;
    const r = Math.floor(i / COLS);
    const x = MARGIN_X + col * (tileW + GAP);
    const y = TOP + r * (tileH + GAP);
    drawBenefitTile(pdf, x, y, tileW, tileH, tile.label, tile.value, tile.sub);
  }
}

function drawBenefitTile(
  pdf: jsPDF,
  x: number,
  y: number,
  w: number,
  h: number,
  label: string,
  value: string,
  sub?: string,
) {
  setFill(pdf, COLOR.cardBgAlt);
  pdf.roundedRect(x, y, w, h, 6, 6, 'F');
  setStroke(pdf, COLOR.hairline);
  pdf.setLineWidth(0.6);
  pdf.roundedRect(x, y, w, h, 6, 6, 'S');

  // Left accent stripe — narrow vertical bar in primary.
  setFill(pdf, COLOR.primary);
  pdf.rect(x, y + 8, 3, h - 16, 'F');

  // Label
  setText(pdf, COLOR.muted);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(7);
  pdf.text(asciiSafe(label.toUpperCase()), x + 14, y + 18);

  // Value (large)
  setText(pdf, COLOR.ink);
  pdf.setFont('times', 'normal');
  pdf.setFontSize(20);
  const valueLines = pdf.splitTextToSize(asciiSafe(value), w - 24) as string[];
  pdf.text(valueLines[0] || '', x + 14, y + 46);

  // Sub
  if (sub) {
    setText(pdf, COLOR.muted);
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(8);
    const subLines = pdf.splitTextToSize(asciiSafe(sub), w - 24) as string[];
    pdf.text(subLines[0] || '', x + 14, y + h - 12);
  }
}

// ─── Section: covered services chips ─────────────────────────────

function drawCoveredServices(pdf: jsPDF, h: Highlights) {
  const TOP = 510;
  setText(pdf, COLOR.primary);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(8);
  pdf.text(asciiSafe('COVERED SERVICES'), MARGIN_X, TOP);

  setStroke(pdf, COLOR.hairline);
  pdf.setLineWidth(0.5);
  pdf.line(MARGIN_X + 108, TOP - 3, PAGE_W - MARGIN_X, TOP - 3);

  if (h.coveredServices.length === 0) {
    setText(pdf, COLOR.muted);
    pdf.setFont('helvetica', 'italic');
    pdf.setFontSize(9);
    pdf.text(asciiSafe('No service-type detail returned by payer.'), MARGIN_X, TOP + 18);
    return;
  }

  // Wrap chips across up to 3 lines.
  let cx = MARGIN_X;
  let cy = TOP + 18;
  const lineH = 22;
  const maxRight = PAGE_W - MARGIN_X;
  for (const svc of h.coveredServices) {
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(9);
    const text = asciiSafe(svc);
    const w = pdf.getTextWidth(text) + 18;
    if (cx + w > maxRight) {
      cx = MARGIN_X;
      cy += lineH;
      if (cy > TOP + 18 + lineH * 2) break;
    }
    setFill(pdf, COLOR.emeraldBg);
    pdf.roundedRect(cx, cy - 11, w, 16, 8, 8, 'F');
    setText(pdf, COLOR.emerald);
    pdf.text(text, cx + 9, cy);
    cx += w + 6;
  }
}

// ─── Section: warnings / aaaErrors ───────────────────────────────

function drawWarnings(pdf: jsPDF, h: Highlights) {
  if (h.warnings.length === 0) return;
  const TOP = 600;
  const HMAX = 70;

  setFill(pdf, COLOR.amberBg);
  pdf.roundedRect(MARGIN_X, TOP, PAGE_W - MARGIN_X * 2, HMAX, 6, 6, 'F');
  setStroke(pdf, '#e7c177');
  pdf.setLineWidth(0.6);
  pdf.roundedRect(MARGIN_X, TOP, PAGE_W - MARGIN_X * 2, HMAX, 6, 6, 'S');

  // Tag stripe
  setFill(pdf, COLOR.amber);
  pdf.rect(MARGIN_X, TOP, 3, HMAX, 'F');

  setText(pdf, COLOR.amber);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(8);
  pdf.text(asciiSafe('REVIEW REQUIRED'), MARGIN_X + 14, TOP + 16);

  setText(pdf, COLOR.body);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(9);
  let wy = TOP + 30;
  for (const w of h.warnings.slice(0, 3)) {
    const wrapped = pdf.splitTextToSize(asciiSafe(`- ${w}`), PAGE_W - MARGIN_X * 2 - 24) as string[];
    for (const line of wrapped.slice(0, 1)) {
      pdf.text(line, MARGIN_X + 14, wy);
      wy += 12;
      if (wy > TOP + HMAX - 6) break;
    }
    if (wy > TOP + HMAX - 6) break;
  }
}

// ─── Section: footer band ────────────────────────────────────────

function drawFooterBand(pdf: jsPDF, row: EligibilityPdfRow) {
  const H = 56;
  const TOP = PAGE_H - H;
  setFill(pdf, COLOR.deep);
  pdf.rect(0, TOP, PAGE_W, H, 'F');

  // Top accent stripe
  setFill(pdf, COLOR.primary);
  pdf.rect(0, TOP - 3, PAGE_W, 3, 'F');

  setText(pdf, COLOR.white);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(9);
  pdf.text(asciiSafe('SEVEN ARROWS RECOVERY'), MARGIN_X, TOP + 22);

  setText(pdf, '#d8c8b8');
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(8);
  pdf.text(asciiSafe('Boutique residential addiction treatment - Cochise County, Arizona'), MARGIN_X, TOP + 36);
  pdf.setFontSize(7);
  setText(pdf, '#a89484');
  pdf.text(asciiSafe('sevenarrowsrecoveryarizona.com'), MARGIN_X, TOP + 48);

  // Right side: generated stamp + trace metadata
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(7);
  setText(pdf, '#d8c8b8');
  const gen = new Date().toLocaleString('en-US', {
    month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit',
  });
  pdf.text(asciiSafe(`Generated ${gen}`), PAGE_W - MARGIN_X, TOP + 22, { align: 'right' });

  const meta = row.eligibility_response?.meta as Record<string, unknown> | undefined;
  const traceId = (meta?.traceId as string | undefined) || row.id;
  pdf.text(asciiSafe(`Trace ${traceId.slice(0, 40)}`), PAGE_W - MARGIN_X, TOP + 36, { align: 'right' });

  setText(pdf, '#a89484');
  pdf.text(
    asciiSafe('Verified via Stedi (270/271) - Confidential, for treatment-team use only.'),
    PAGE_W - MARGIN_X,
    TOP + 48,
    { align: 'right' },
  );
}
